about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

templates/includes/author_card.html
<div class="card">
    <div class="card-body">
        <div class="h2" style="color:#6f42c1">
            <!-- Имя автора -->
            {{ author.get_full_name }}
        </div>

    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчики: {{ followers }} <br />
                Подписки: {{ followings }}
            </div>
        </li>
        <li class="list-group-item">
            <div class="h6 text-muted">
                <!-- Количество записей -->
                Записей: {{ count }}
            </div>
        </li>
        {% if user.is_authenticated and author != user %}
        <li class="list-group-item">
            {% if following %}
            <a class="btn btn-lg btn-light"
                    href="{% url 'profile_unfollow' author.username %}" role="button">
                    Отписаться
            </a>
            {% else %}
            <a class="btn btn-outline-success"
                    href="{% url 'profile_follow' author.username %}" role="button">
            Подписаться
            </a>
            {% endif %}
        </li>
        {% endif %}
    </ul>
</div>

templates/includes/comments.html
{% load user_filters %}

<!-- Комментарии -->
{% for item in comments %}
<div class="card mb-3 mt-1 shadow-sm">
    <div class="media-body card-body">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="mt-0">

                <a href="{% url 'profile' item.author.username %}"
                   name="comment_{{ item.id }}" style="color:#6f42c1">
                    {{ item.author.username }}
                </a>
            </h5>
            <small class="text-muted">{{ item.created|date:"d M Y" }}</small>
        </div>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

<!-- Форма добавления комментария -->
{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'add_comment' post.author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-success">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top" style="background-color: #96ffc5;">
    <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:#6f42c1">Ya</span><span style="color:#fd7e14">tube</span> © {% now 'Y' %}, все права защищены.</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #96ffc5;">
    <a class="navbar-brand" href="{% url 'index' %}">
        <strong>
        <span style="color:#6f42c1">Ya</span><span style="color:#fd7e14">tube</span>
        </strong>
    </a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-success" href="{% url 'group_create' %}" role="button">Создать группу</a>
        <a class="btn btn-success" href="{% url 'new_post' %}" role="button">Новая запись</a>
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "600x350" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
        <div class="card-body">
            <p class="card-text">
                <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                <a href="{% url 'profile' post.author.username %}"><strong class="d-block" style="color:#6f42c1">@{{ post.author.username }}</strong></a>

            {{ post.text }}</p>

            {% if post.group %}
            <a class="card-link muted" href="{% url 'group' post.group.slug %}">
                <strong class="d-block" style="color:#fd7e14">{{ post.group.title }}</strong>
            </a>
            {% endif %}

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group ">
                    {% if post.comments.exists %}
                    <div>
                      Комментариев: {{ post.comments.count }}
                    </div>
                    {% endif %}
                    <!-- Ссылка на страницу записи в атрибуте href-->
                    <a class="btn btn-sm text-muted" href="{% url 'add_comment' post.author.username post.id %}" role="button">Добавить комментарий</a>
                    {% if user == post.author %}<!-- Ссылка на редактирование, показывается только автору записи -->
                        <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id %}" role="button">Редактировать</a>
                    {% endif %}
                </div>
                <!-- Дата публикации  -->
                <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>

            </div>
            {% if not forloop.last %}<hr>{% endif %}

        </div>
</div>